apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
  labels:
    app: petclinic
spec:
  selector:
    app: petclinic
  type: LoadBalancer
  ports:
    -  protocol: TCP
       port: 80
       targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-dep
  labels:
    app: petclinic
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: petclinic
  strategy:
    rollingUpdate:
      # maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - image: <ECR_URI>:latest
          imagePullPolicy: Always
          name: petclinic
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
          securityContext:
            runAsUser: 1000
          ports:
            - containerPort: 8080
              protocol: TCP

